# Generated by Django 2.1.2 on 2018-10-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20181014_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='username',
            name='user',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
