# Generated by Django 2.1.2 on 2018-10-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20181014_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='username',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
