# Generated by Django 2.1.2 on 2018-10-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20181014_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresarProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
            ],
        ),
    ]
