# Generated by Django 2.1.2 on 2018-10-15 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaMatricual', models.DateTimeField(auto_now_add=True)),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Alumno')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Carrera')),
            ],
        ),
    ]
