# Generated by Django 2.1.2 on 2018-10-15 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_matriculacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculacion',
            name='fechaMatricual',
        ),
        migrations.AddField(
            model_name='matriculacion',
            name='fechaMatricula',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 7, 30, 15, 926774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=52),
        ),
    ]
